-- =====================================================================
-- AtmoSync Snowflake DDL - Initial Setup
-- Database: ATMOSYNC
-- Schemas: RAW, STAGING, ANALYTICS
-- =====================================================================

-- Create Database
CREATE DATABASE IF NOT EXISTS ATMOSYNC;
USE DATABASE ATMOSYNC;

-- Create Schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

USE SCHEMA RAW;

-- 1. Raw Telemetry Table
CREATE TABLE IF NOT EXISTS RAW.RAW_TELEMETRY (
    EVENT_ID VARCHAR(64) NOT NULL,
    CONTAINER_ID VARCHAR(32) NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    TEMPERATURE NUMBER(5,2),
    HUMIDITY NUMBER(5,2),
    VIBRATION NUMBER(5,3),
    LATITUDE NUMBER(9,6),
    LONGITUDE NUMBER(9,6),
    ORIGIN VARCHAR(64),
    DESTINATION VARCHAR(64),
    COMMODITY VARCHAR(64),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RAW_PAYLOAD VARIANT,
    PRIMARY KEY (EVENT_ID)
);

-- 2. Raw Commodity Spot Pricing Table
CREATE TABLE IF NOT EXISTS RAW.COMMODITY_PRICING (
    PRICE_ID VARCHAR(64) DEFAULT UUID_STRING(),
    COMMODITY VARCHAR(64) NOT NULL,
    MARKET VARCHAR(64) NOT NULL,
    PRICE_PER_UNIT_INR NUMBER(10,2) NOT NULL,
    CURRENCY VARCHAR(8) DEFAULT 'INR',
    EFFECTIVE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Container Metadata Reference Table
CREATE TABLE IF NOT EXISTS RAW.CONTAINER_METADATA (
    CONTAINER_ID VARCHAR(32) PRIMARY KEY,
    COMMODITY VARCHAR(64),
    ORIGIN VARCHAR(64),
    DESTINATION VARCHAR(64),
    SAFE_TEMP_MIN NUMBER(5,2),
    SAFE_TEMP_MAX NUMBER(5,2),
    SAFE_HUMIDITY_MIN NUMBER(5,2),
    SAFE_HUMIDITY_MAX NUMBER(5,2),
    SPOILAGE_HOURS_THRESHOLD NUMBER(5,2),
    CARGO_BASE_VALUE_INR NUMBER(12,2)
);

-- 4. Candidate Market Locations Reference Table
CREATE TABLE IF NOT EXISTS RAW.MARKET_LOCATIONS (
    MARKET_NAME VARCHAR(64) PRIMARY KEY,
    STATE VARCHAR(64),
    LATITUDE NUMBER(9,6) NOT NULL,
    LONGITUDE NUMBER(9,6) NOT NULL,
    PORT_TYPE VARCHAR(32)
);
